import { PointerEvent, useEffect } from "react";
import type { CSSProperties } from "react";
import { DrawerMode, DrawerTab, LocalSettings, Run } from "../types";
import { AIComposer } from "./AIComposer";
import { Diagnostics } from "./Diagnostics";
import { Settings } from "./Settings";
import { VersionHistory } from "./VersionHistory";

type Props = { open: boolean; mode: DrawerMode; width: number; tab: DrawerTab; run?: Run; selectedNode: string; settings: LocalSettings; onClose: () => void; onMode: (mode: DrawerMode) => void; onTab: (tab: DrawerTab) => void; onResize: (width: number) => void; onSettings: (settings: LocalSettings) => void; onPropose: () => void };
const tabs: { id: DrawerTab; label: string }[] = [{ id: "assistant", label: "Assistant" }, { id: "inspector", label: "Inspector" }, { id: "activity", label: "Activity" }, { id: "versions", label: "Versions" }, { id: "diagnostics", label: "Diagnostics" }, { id: "settings", label: "Data & Trust" }];

export function ContextDrawer(props: Props) {
  const { open, mode, width, tab, run, selectedNode, settings, onClose, onMode, onTab, onResize, onSettings, onPropose } = props;
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape" && open) onClose(); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [open, onClose]);
  const resize = (event: PointerEvent<HTMLDivElement>) => { const startX = event.clientX; const startWidth = width; const move = (moveEvent: globalThis.PointerEvent) => onResize(Math.min(560, Math.max(300, startWidth + (mode === "docked" ? startX - moveEvent.clientX : 0)))); const up = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up); };
  if (!open) return null;
  return <><div className={mode === "overlay" ? "drawer-backdrop" : "drawer-backdrop hidden"} onClick={onClose} aria-hidden="true" /><aside className={`context-drawer ${mode}`} style={{ "--drawer-width": `${width}px` } as CSSProperties} aria-label="Contextual workspace tools"><div className="resize-handle" onPointerDown={resize} onDoubleClick={() => onResize(380)} role="separator" aria-orientation="vertical" aria-label="Resize context drawer" tabIndex={0} onKeyDown={event => { if (event.key === "ArrowLeft") onResize(Math.min(560, width + 20)); if (event.key === "ArrowRight") onResize(Math.max(300, width - 20)); }} /><div className="drawer-header"><div><span className="eyebrow">CONTEXT TOOLS</span><b>{tabs.find(item => item.id === tab)?.label}</b></div><div><button className="icon-button" title={mode === "docked" ? "Use overlay drawer" : "Dock drawer"} onClick={() => onMode(mode === "docked" ? "overlay" : "docked")}>{mode === "docked" ? "▧" : "▥"}</button><button className="icon-button" title="Close context drawer" onClick={onClose}>×</button></div></div><div className="drawer-tabs" role="tablist">{tabs.map(item => <button key={item.id} role="tab" aria-selected={tab === item.id} className={tab === item.id ? "active" : ""} onClick={() => onTab(item.id)}>{item.label}</button>)}</div><div className="drawer-content">{tab === "assistant" && <><div className="assistant-intro"><b>Ask in context</b><p>The assistant will use the selected node, the current pipeline, and approved references.</p></div><AIComposer onPropose={onPropose} /><details><summary>Run details</summary><p>Provider-neutral local runtime · {run?.token_usage.input_tokens ?? 0} input tokens · trace {run?.trace_id ?? "pending"}</p></details></>}{tab === "inspector" && <div className="drawer-stack"><span className="eyebrow">SELECTED NODE</span><h3>{selectedNode}</h3><p className="muted">Dependencies and data flow are explicit in the validated graph.</p><dl className="diagnostic-list"><dt>Scope</dt><dd>Current pipeline</dd><dt>Policy</dt><dd>Approved evidence only</dd><dt>Budget</dt><dd>{run ? `${run.token_usage.context_tokens} context tokens used` : "Available on run"}</dd></dl><button className="quiet-button" onClick={onPropose}>Explain this node with AI</button></div>}{tab === "activity" && <div className="drawer-stack"><span className="eyebrow">RUN ACTIVITY</span>{run?.node_executions.map(node => <div className="activity-row" key={`${node.node_id}-${node.iteration ?? 0}`}><span className={`activity-dot ${node.status}`} /><b>{node.node_id}</b><small>{node.status} · {node.duration_ms}ms</small></div>) ?? <p className="muted">Run a pipeline to see node activity.</p>}</div>}{tab === "versions" && <VersionHistory />}{tab === "diagnostics" && <Diagnostics run={run} />}{tab === "settings" && <Settings settings={settings} onChange={onSettings} />}</div></aside></>;
}
