import { Component, Run } from "../types";
import { AIChangeSet } from "./AIChangeSet";

type Props = { components: Component[]; run?: Run; question: string; answer: string; running: boolean; selectedNode: string; proposal: "idle" | "proposed" | "accepted" | "rejected"; onQuestion: (value: string) => void; onRun: () => void; onSelectNode: (node: string) => void; onProposal: (status: "proposed" | "accepted" | "rejected") => void };

const nodes = ["classify", "bm25", "dense", "vectorless", "fuse", "verify", "context", "generate"];

export function PrimaryCanvas({ components, run, question, answer, running, selectedNode, proposal, onQuestion, onRun, onSelectNode, onProposal }: Props) {
  return <section className="primary-canvas" aria-label="Pipeline workspace"><div className="canvas-heading"><div><div className="breadcrumbs">Pipelines <span>/</span> Local workspace <span>/</span> baseline</div><h1>local-evidence-baseline <span>1.0.0</span></h1></div><div className="canvas-actions"><button className="quiet-button" title="Undo last accepted proposal">↶ Undo</button><button className="quiet-button">Export</button><button className="primary-button" onClick={onRun} disabled={running}>{running ? "Running…" : "Run pipeline"}</button></div></div>
    <AIChangeSet status={proposal} onAccept={() => onProposal("accepted")} onReject={() => onProposal("rejected")} onRevise={() => onProposal("proposed")} />
    <section className="canvas-card pipeline-board"><div className="board-toolbar"><div><span className="eyebrow">PIPELINE GRAPH</span><b>Evidence-first baseline</b></div><span className="quiet-status">Validated graph · immutable version</span></div><div className="pipeline-graph" role="list" aria-label="Pipeline nodes">{nodes.map((node, index) => <button key={node} role="listitem" className={`pipeline-node ${selectedNode === node ? "selected" : ""} ${["bm25", "dense", "vectorless"].includes(node) ? "retrieval" : ""}`} onClick={() => onSelectNode(node)}><span>{index + 1}</span>{node.replace("vectorless", "vectorless retrieval")}</button>)}</div><p className="graph-caption">Three explicit retrieval lanes merge before verification. Select a node to inspect its scope and trace details.</p></section>
    <section className="work-grid"><div className="canvas-card question-card"><div className="card-heading"><div><span className="eyebrow">RUN INPUT</span><h2>Ask the active pipeline</h2></div><span className="scope-chip">Approved references only</span></div><label>Question<textarea value={question} onChange={event => onQuestion(event.target.value)} /></label><div className="input-actions"><small>Context: pipeline baseline · corpus policy applied before retrieval</small><button className="primary-button" onClick={onRun} disabled={running}>{running ? "Working…" : "Run"}</button></div></div><div className="canvas-card answer-card"><div className="card-heading"><div><span className="eyebrow">LATEST RESPONSE</span><h2>{run ? (run.status === "completed" ? "Grounded response" : "Run needs attention") : "Ready to run"}</h2></div>{run && <span className={run.status === "completed" ? "status-good" : "status-bad"}>{run.status}</span>}</div><p>{answer}</p>{run && <div className="answer-meta"><span>{run.token_usage.context_tokens} context tokens</span><span>{run.node_executions.length} node events</span><span>Trace available in drawer</span></div>}</div></section>
    <section className="canvas-card catalog-card"><div className="card-heading"><div><span className="eyebrow">COMPONENT CATALOG</span><h2>Choose with evidence</h2></div><button className="quiet-button">Compare</button></div><div className="component-list">{components.slice(0, 5).map(component => <button key={`${component.id}@${component.version}`} className="component-row" onClick={() => onSelectNode(component.id.split(".").at(-1) ?? component.id)}><span className="component-mark">◈</span><span><b>{component.id}</b><small>{component.category} · {component.version}</small></span><em>{component.description}</em></button>)}</div></section>
  </section>;
}
